### ISSUE TITLE
PiT 25.0: project doesn't work with Vaadin 25.0.0-beta6

### ISSUE THREAD

**Issue by ZheSun88** [TatuLund/mpr-demo#58]
when building project with vaadin 25.0.0-beta6, it failed with the following error

```
[WARNING] Failed startup of context oeje10mp.MavenWebAppContext@5de49e5a{ROOT,/,b=[file:///home/runner/work/platform/platform/tmp/mpr-demo/src/main/webapp/, jar:file:///home/runner/.m2/repository/com/vaadin/vaadin-context-menu-flow/25.0.0-beta6/vaadin-context-menu-flow-25.0.0-beta6.jar!/META-INF/res
java.lang.NoClassDefFoundError: oshi/SystemInfo
Caused by: java.lang.ClassNotFoundException: oshi.SystemInfo
```

step to reproduce:

- perl -pi -e 's|(\s*<'vaadin.version'>)[^\s]+(</'vaadin.version'>)|${1}25.0.0-beta6${2}|g' pom.xml
- perl -pi -e 's|(\s*<'flow.version'>)[^\s]+(</'flow.version'>)|${1}25.0.0-beta6${2}|g' pom.xml
- perl -pi -e 's|(\s*<'mpr.version'>)[^\s]+(</'mpr.version'>)|${1}8.0.0-beta1${2}|g' pom.xml
- perl -0777 -pi -e 's|(\n[ 	]*)(</dependencies>\s+(<build>\|<repo\|<dependencyM))|$1 <dependency>$1 <groupId>com.vaadin</groupId>$1 <artifactId>vaadin-dev</artifactId>$1 <scope>compile</scope>$1 </dependency>$1$2|' pom.xml
- adding AnonymousAllowed to ./src/main/java/org/vaadin/mprdemo/MyUI.java
- mvn -ntp -B jetty:run 
- error in the build log

**Comment by mcollovati** [comment]
Looks like there is an old version of License Checker shaded into `vaadin-server-mpr-jakarta` artifact

**Comment by mcollovati** [comment]
Works with Vaadin Framework 8.26+
